---
title: "Model Building Practice"
output: html_document
date: "2023-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls()) #Clear environment

#Load necessary packages
library(ISLR) 
library(corrplot)
Smarket <- Smarket

#Look for correlations
correlations <- cor(Smarket[,1:8])
corrplot(correlations, method="circle")

#Try to identify Patterns
library(caret)
x <- Smarket[,1:8]
y <- Smarket[,9]
scales <- list(x=list(relation="free"), y=list(relation="free"))
featurePlot(x=x, y=y, plot="density", scales=scales)

#Basic Model
glm.fit <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data = Smarket, family = binomial)
summary(glm.fit)

#Glimpse of first 5 predictions
glm.probs <- predict(glm.fit,type = "response")
glm.probs[1:5]

glm.pred <- ifelse(glm.probs > 0.5, "Up", "Down")

attach(Smarket)
table(glm.pred,Direction)
mean(glm.pred == Direction)

#Hold on, we need test and training
set.seed(100)

#create ID variable
Smarket$id <- 1:nrow(Smarket)

#Use 70% of dataset as training set and remaining 30% as testing set 
train <- Smarket %>% dplyr::sample_frac(0.7)
test  <- dplyr::anti_join(Smarket, train, by = 'id')

#Create model using training data
glm.fit <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
               data = train,
               family = binomial)

glm.probs <- predict(glm.fit,
                    newdata = test,
                    type = "response")

glm.pred <- ifelse(glm.probs > 0.5, "Up", "Down")


table(glm.pred, test$Direction)
mean(glm.pred == test$Direction)

summary(glm.fit)


# Fit a smaller model
glm.fit2 = glm(Direction ~ Lag1 + Lag2, data = train, family = binomial)

anova(glm.fit,glm.fit2, test="Chisq")

glm.probs2 = predict(glm.fit2, newdata = test, type = "response")
glm.pred2 = ifelse(glm.probs2 > 0.5, "Up", "Down")
table(glm.pred2, test$Direction)

mean(glm.pred2 == test$Direction) #0.539

```


